### ISSUE TITLE
Grouping of the column no longer works

### ISSUE THREAD

**Issue by SergeyVoskoboynikov** [MaStr11/DXFilterPopupEmployees#2]
In der Version 21.1.6 wird die Spalte der Teams nicht mehr als gruppiert dargestellt.
![image](https://user-images.githubusercontent.com/32773129/142986397-bdc8677b-6936-49b3-a7d7-0eb3ed912472.png)

Festgestellt in https://github.com/ifpanalytics/ares.plan/pull/387#issue-1060941796.

**Comment by MaStr11** [comment]
Ich schau mir das mal an.

**Comment by MaStr11** [comment]
In diesem Testprojekt geht es nach dem Update auf 21.1.6:
![image](https://user-images.githubusercontent.com/24472128/142995317-bb9aa960-3428-4626-91b7-2a0cb002de17.png)

![image](https://user-images.githubusercontent.com/24472128/142995602-aa24901f-b0f5-4057-918e-311ac23a80dd.png)

**Comment by SergeyVoskoboynikov** [comment]
Fixed in https://github.com/ifpanalytics/ares.plan/pull/388#issue-1061090569.
